"""init

Revision ID: 05cc62626ad2
Revises: 
Create Date: 2026-02-04 04:00:58.011433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cc62626ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_process', 'process',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dim_process', 'product',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dim_worker', 'process',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('dim_worker', 'worker_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('dim_worker_process_worker_name_key'), 'dim_worker', type_='unique')
    op.create_unique_constraint('uq_dim_worker_process_name', 'dim_worker', ['process', 'worker_name'])
    op.alter_column('fact_production_daily', 'process',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_production_daily', 'process',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_dim_worker_process_name', 'dim_worker', type_='unique')
    op.create_unique_constraint(op.f('dim_worker_process_worker_name_key'), 'dim_worker', ['process', 'worker_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('dim_worker', 'worker_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dim_worker', 'process',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dim_process', 'product',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('dim_process', 'process',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
